module.exports = [
  { name: "Paracetamol 500mg", price: 30, category: "Medicine", rating: 4.5, reviews: 120, uses: "Relieves mild to moderate pain and reduces fever.", warning: "Do not exceed 4000mg per day. Avoid alcohol.", limit: "1-2 tablets every 4-6 hours max.", expiry: "Dec 2026", beforeUse: "Store below 25°C in a dry place.", imageUrl: "/images/medicines/paracetamol_500mg_1774028012018.png" },
  { name: "Vitamin C Tablets", price: 50, category: "Medicine", rating: 4.8, reviews: 85, uses: "Boosts immune system and treats vitamin C deficiency.", warning: "High doses may cause stomach cramps or diarrhea.", limit: "1 tablet daily after meal.", expiry: "Mar 2026", beforeUse: "Keep bottle tightly closed.", imageUrl: "/images/medicines/vitamin_c_tablets_1774028034331.png" },
  { name: "Amoxicillin", price: 80, category: "Medicine", rating: 4.2, reviews: 45, uses: "Antibiotic used to treat bacterial infections.", warning: "Requires prescription. Complete full course. May cause allergic reactions in some.", limit: "Usually 500mg every 8-12 hours.", expiry: "Oct 2025", beforeUse: "Consume full course once started.", imageUrl: "/images/medicines/amoxicillin_1774028052407.png" },
  { name: "Cetirizine", price: 40, category: "Medicine", rating: 4.6, reviews: 60, uses: "Treats allergic symptoms like sneezing, runny nose.", warning: "May cause drowsiness. Do not drive if affected.", limit: "1 tablet per day.", expiry: "Jan 2027", beforeUse: "Protect from direct sunlight.", imageUrl: "/images/medicines/cetirizine_1774028069738.png" },
  { name: "Aspirin 100mg", price: 25, category: "Medicine", rating: 4.3, reviews: 30, uses: "Pain relief and blood thinner to prevent heart attacks.", warning: "Do not give to children. May cause stomach bleeding.", limit: "As directed by a doctor.", expiry: "Nov 2025", beforeUse: "Do not use if seal is broken.", imageUrl: "/images/medicines/aspirin_100mg_1774028090847.png" },
  { name: "Metformin 500mg", price: 65, category: "Medicine", rating: 4.7, reviews: 110, uses: "Controls high blood sugar in type 2 diabetes.", warning: "May cause lactic acidosis. Take with meals.", limit: "Max 2000mg/day depending on doctor prescription.", expiry: "Aug 2026", beforeUse: "Store below 30°C.", imageUrl: "/images/medicines/metformin_500mg_1774028108849.png" },
  { name: "Atorvastatin 10mg", price: 120, category: "Medicine", rating: 4.4, reviews: 95, uses: "Lowers 'bad' cholesterol and fats in blood.", warning: "May cause muscle pain. Avoid grapefruit juice.", limit: "1 tablet daily.", expiry: "Sep 2026", beforeUse: "Keep out of reach of children.", imageUrl: "/images/medicines/atorvastatin_10mg_1774028129882.png" },
  { name: "Digital Thermometer", price: 150, category: "Device", rating: 4.5, reviews: 200, uses: "Measures body temperature accurately.", warning: "Keep out of reach of infants. Do not immerse in boiling water.", limit: "No usage limit, change battery periodically.", expiry: "N/A (Battery ~2 yrs)", beforeUse: "Calibrate before first use.", imageUrl: "/images/medicines/digital_thermometer_1774028145612.png" },
  { name: "BP Monitor", price: 1200, category: "Device", rating: 4.9, reviews: 150, uses: "Monitors blood pressure levels at home.", warning: "Not a substitute for doctor consultation. Calibrate yearly.", limit: "Use as needed.", expiry: "N/A (Warranty 3 yrs)", beforeUse: "Read manual thoroughly.", imageUrl: "/images/medicines/bp_monitor_1774028164696.png" },
  { name: "Pulse Oximeter", price: 899, category: "Device", rating: 4.6, reviews: 80, uses: "Measures blood oxygen levels (SpO2) and pulse.", warning: "Nail polish may affect reading accuracy.", limit: "Use as needed.", expiry: "N/A (Warranty 1 yr)", beforeUse: "Clean sensor before use.", imageUrl: "/images/medicines/pulse_oximeter_1774028180159.png" },
  { name: "Glucometer Kit", price: 1450, category: "Device", rating: 4.8, reviews: 65, uses: "Monitors blood glucose levels for diabetics.", warning: "Use fresh test strips. Do not share lancets.", limit: "Depends on monitoring frequency prescribed.", expiry: "Strips exp: Aug 2025", beforeUse: "Check strip codes match meter.", imageUrl: "/images/medicines/glucometer_kit_1774028208155.png" },
  { name: "Nebulizer Machine", price: 2100, category: "Device", rating: 4.3, reviews: 40, uses: "Delivers medication directly to the lungs.", warning: "Clean parts after every use to prevent infection.", limit: "Use as prescribed for respiratory conditions.", expiry: "N/A (Warranty 2 yrs)", beforeUse: "Sterilize attachments.", imageUrl: "/images/medicines/nebulizer_machine_1774028228172.png" },
  { name: "Face Wash", price: 199, category: "Personal Care", rating: 4.2, reviews: 300, uses: "Cleanses skin and removes impurities.", warning: "Avoid contact with eyes. For external use only.", limit: "Use twice daily.", expiry: "May 2026", beforeUse: "Use within 6 months of opening.", imageUrl: "/images/medicines/face_wash_1774028241826.png" },
  { name: "Hand Sanitizer", price: 99, category: "Personal Care", rating: 4.5, reviews: 500, uses: "Kills 99.9% germs on hands instantly.", warning: "Flammable. Keep away from fire. Do not swallow.", limit: "Use as needed.", expiry: "Jul 2025", beforeUse: "Keep away from heat.", imageUrl: "/images/medicines/hand_sanitizer_1774028262239.png" },
  { name: "Sunscreen SPF 50", price: 450, category: "Personal Care", rating: 4.7, reviews: 180, uses: "Protects skin from harmful UV sun rays.", warning: "Reapply every 2-3 hours if swimming or sweating.", limit: "Apply generously 15 mins before sun exposure.", expiry: "Apr 2026", beforeUse: "Shake well before use.", imageUrl: "/images/medicines/sunscreen_spf_50_1774028279799.png" },
  { name: "Moisturizing Lotion", price: 320, category: "Personal Care", rating: 4.6, reviews: 220, uses: "Hydrates and softens dry skin.", warning: "If irritation occurs, discontinue use.", limit: "Apply daily as required.", expiry: "Jan 2027", beforeUse: "Use within 12 months of opening.", imageUrl: "/images/medicines/moisturizing_lotion_1774028295234.png" },
  { name: "Surgical Mask (50pcs)", price: 250, category: "Surgicals", rating: 4.8, reviews: 1000, uses: "Provides protection against airborne particles.", warning: "Single use only. Do not wash and reuse.", limit: "Change every 4-6 hours or if soiled.", expiry: "Feb 2028", beforeUse: "Store in dry place.", imageUrl: "/images/medicines/surgical_mask_1774028314475.png" },
  
  // High quality distinct Unsplash photography 
  { name: "Crepe Bandage", price: 110, category: "Surgicals", rating: 4.1, reviews: 50, uses: "Provides support for sprains and strains.", warning: "Do not wrap too tightly; may restrict blood flow.", limit: "Use as needed until healed.", expiry: "N/A (Replace when stretched)", beforeUse: "Wash gently if reused.", imageUrl: "/images/medicines/crepe_bandage.png" },
  { name: "Sterile Gauze", price: 45, category: "Surgicals", rating: 4.4, reviews: 75, uses: "For cleaning and covering wounds.", warning: "Do not use if package is opened or damaged.", limit: "Change daily or as instructed by doctor.", expiry: "Sep 2027", beforeUse: "Use immediately upon opening.", imageUrl: "/images/medicines/sterile_gauze.png" },
  { name: "Fitness Band", price: 2499, category: "Fitness", rating: 4.5, reviews: 400, uses: "Tracks steps, heart rate, and workouts.", warning: "Not a medical device. Measurements are estimates.", limit: "Wear continuously if desired.", expiry: "N/A", beforeUse: "Charge fully before first use.", imageUrl: "/images/medicines/fitness_band.png" },
  { name: "Whey Protein 1kg", price: 1899, category: "Fitness", rating: 4.9, reviews: 600, uses: "Helps in muscle building and recovery.", warning: "Consult doctor if you have kidney issues. Contains dairy.", limit: "Usually 1-2 scoops per day based on workout.", expiry: "Mar 2025", beforeUse: "Consume within 3 months of opening.", imageUrl: "/images/medicines/whey_protein.png" },
  { name: "Yoga Mat", price: 799, category: "Fitness", rating: 4.7, reviews: 350, uses: "Provides cushioning and non-slip surface for exercise.", warning: "Keep away from direct sharp objects or prolonged sun.", limit: "Use as needed.", expiry: "N/A", beforeUse: "Wipe with damp cloth.", imageUrl: "/images/medicines/yoga_mat.png" },
  { name: "Pet Shampoo", price: 299, category: "Pet Care", rating: 4.6, reviews: 120, uses: "Cleanses and deodorizes pet's coat.", warning: "Avoid contact with pets' eyes and ears.", limit: "Use once every 1-2 weeks.", expiry: "Oct 2026", beforeUse: "Dilute with water before use.", imageUrl: "/images/medicines/pet_shampoo.png" },
  { name: "Tick & Flea Spray", price: 450, category: "Pet Care", rating: 4.3, reviews: 90, uses: "Kills and repels ticks, fleas, and lice on pets.", warning: "Do not spray on eyes or mouth. Wash hands after use.", limit: "Apply based on product instructions.", expiry: "Nov 2025", beforeUse: "Shake vigorously.", imageUrl: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=400&fit=crop" },
  { name: "Pet Multivitamins", price: 350, category: "Pet Care", rating: 4.8, reviews: 55, uses: "Supports overall pet health and immunity.", warning: "For animal use only. Keep out of reach of children.", limit: "Usually 1 tablet/syrup dose daily.", expiry: "Jul 2025", beforeUse: "Store tightly sealed.", imageUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?q=80&w=400&fit=crop" },
  { name: "Ayush Kadha", price: 180, category: "Ayush", rating: 4.7, reviews: 250, uses: "Ayurvedic immunity booster to fight cold/cough.", warning: "May cause mild heat in body, avoid overconsumption.", limit: "1 cup daily.", expiry: "Dec 2026", beforeUse: "Mix well in boiling water.", imageUrl: "https://images.unsplash.com/photo-1564858025217-48f07fb0b9fe?q=80&w=400&fit=crop" },
  { name: "Ashwagandha Powder", price: 240, category: "Ayush", rating: 4.6, reviews: 140, uses: "Reduces stress and boosts energy optionally.", warning: "Pregnant women should consult a doctor before use.", limit: "1/2 to 1 tsp daily with milk or water.", expiry: "Aug 2025", beforeUse: "Keep away from moisture.", imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=400&fit=crop" },
  { name: "Triphala Churna", price: 150, category: "Ayush", rating: 4.5, reviews: 110, uses: "Relieves constipation and improves digestion.", warning: "Overuse may cause loose stools. Consult physician.", limit: "1 tsp before sleep.", expiry: "Feb 2026", beforeUse: "Consume with lukewarm water.", imageUrl: "https://images.unsplash.com/photo-1596541223130-5d56a73fb116?q=80&w=400&fit=crop" },
  { name: "Homeo Cold Drops", price: 95, category: "Homeopathy", rating: 4.2, reviews: 85, uses: "Homeopathic remedy for runny nose and cold.", warning: "Keep 30 mins gap between meals and medicine.", limit: "10-15 drops in water, 3 times a day.", expiry: "Jan 2027", beforeUse: "Store away from strong odors.", imageUrl: "https://images.unsplash.com/photo-1628771457497-7c050a41d73c?q=80&w=400&fit=crop" },
  { name: "Homeo Digest Syrup", price: 130, category: "Homeopathy", rating: 4.4, reviews: 60, uses: "Alleviates indigestion, gas, and acidity naturally.", warning: "Keep away from strong-smelling substances like camphor.", limit: "1-2 teaspoons thrice daily.", expiry: "Jun 2026", beforeUse: "Shake well before use.", imageUrl: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?q=80&w=400&fit=crop" },
  { name: "Ibuprofen 400mg", price: 45, category: "Medicine", rating: 4.6, reviews: 310, uses: "Relieves pain from various conditions such as headache, dental pain, menstrual cramps.", warning: "Take with food to prevent stomach upset.", limit: "Every 6-8 hours as needed. Max 3200mg/day.", expiry: "Oct 2027", beforeUse: "Store at room temperature.", imageUrl: "https://images.unsplash.com/photo-1550572017-edb79a0cfb2e?q=80&w=400&fit=crop" },
  { name: "Omeprazole 20mg", price: 55, category: "Medicine", rating: 4.8, reviews: 154, uses: "Treats certain stomach and esophagus problems (such as acid reflux, ulcers).", warning: "May take 1 to 4 days for full effect.", limit: "1 capsule daily before a meal.", expiry: "Sep 2026", beforeUse: "Do not chew or crush.", imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=400&fit=crop" },

  // First Aid Segment
  { name: "Complete First Aid Kit", price: 1200, category: "First Aid", rating: 4.8, reviews: 210, uses: "Comprehensive care for minor emergencies.", warning: "Check expiry of individual items.", limit: "Keep handy at home or travel.", expiry: "Dec 2028", beforeUse: "Read included manual.", imageUrl: "/images/medicines/first_aid_kit.png" },
  { name: "Antiseptic Liquid", price: 150, category: "First Aid", rating: 4.6, reviews: 340, uses: "Cleanses wounds and prevents infection.", warning: "For external use only.", limit: "Dilute in water if applying on large areas.", expiry: "Jan 2027", beforeUse: "Wipe area clean first.", imageUrl: "/images/medicines/antiseptic_liquid.png" },
  { name: "Medical Tape", price: 80, category: "First Aid", rating: 4.5, reviews: 120, uses: "Secures bandages and dressings.", warning: "Do not apply directly to open wound.", limit: "Use as needed.", expiry: "N/A", beforeUse: "Ensure skin is dry.", imageUrl: "/images/medicines/medical_tape.png" },
  { name: "Cotton Swabs", price: 60, category: "First Aid", rating: 4.3, reviews: 500, uses: "Precise application of ointments.", warning: "Do not insert deep into ear canal.", limit: "Single use.", expiry: "N/A", beforeUse: "Keep in a cool dry place.", imageUrl: "/images/medicines/cotton_swabs.png" },
  { name: "Burn Healing Ointment", price: 120, category: "First Aid", rating: 4.7, reviews: 85, uses: "Soothes and heals minor burns.", warning: "Do not use on severe 3rd degree burns.", limit: "Apply thin layer 2-3 times daily.", expiry: "Aug 2026", beforeUse: "Run burn under cool water first.", imageUrl: "/images/medicines/burn_ointment.png" },

  // Ayush Segment
  { name: "Giloy Tablets", price: 250, category: "Ayush", rating: 4.6, reviews: 140, uses: "Boosts immunity naturally.", warning: "Consult doctor if pregnant.", limit: "1-2 tablets daily.", expiry: "May 2026", beforeUse: "Take with warm water.", imageUrl: "/images/medicines/giloy_tablets.png" },
  { name: "Tulsi Drops", price: 180, category: "Ayush", rating: 4.8, reviews: 310, uses: "Relieves cough and cold symptoms.", warning: "Do not consume undiluted.", limit: "5 drops in water/tea twice daily.", expiry: "Mar 2027", beforeUse: "Shake well.", imageUrl: "/images/medicines/tulsi_drops.png" },
  { name: "Amla Juice 1L", price: 220, category: "Ayush", rating: 4.5, reviews: 290, uses: "Rich in Vitamin C, aids digestion.", warning: "Consume within 30 days of opening.", limit: "20ml diluted in water every morning.", expiry: "Dec 2025", beforeUse: "Refrigerate after opening.", imageUrl: "/images/medicines/amla_juice.png" },

  // Homeopathy
  { name: "Homeo Hair Care Drops", price: 160, category: "Homeopathy", rating: 4.2, reviews: 90, uses: "Reduces hair fall and dandruff.", warning: "Avoid strong odors like coffee 30 mins before.", limit: "10 drops thrice a day.", expiry: "Oct 2027", beforeUse: "Dilute in water.", imageUrl: "/images/medicines/homeo_hair_drops.png" },
  { name: "Homeo Sleep Aid", price: 200, category: "Homeopathy", rating: 4.4, reviews: 110, uses: "Relieves sleeplessness and anxiety.", warning: "Do not use with alcohol.", limit: "15 drops before bed.", expiry: "Jan 2028", beforeUse: "Avoid brushing teeth right after.", imageUrl: "/images/medicines/homeo_sleep_aid.png" },

  // Pet Care
  { name: "Pet Paw Balm", price: 350, category: "Pet Care", rating: 4.9, reviews: 230, uses: "Moisturizes dry and cracked pet paws.", warning: "Prevent pet from licking for 5 mins.", limit: "Apply as needed.", expiry: "Jun 2026", beforeUse: "Wipe paw before applying.", imageUrl: "/images/medicines/pet_paw_balm.png" },
  { name: "Dog Dental Chews", price: 420, category: "Pet Care", rating: 4.7, reviews: 400, uses: "Reduces tartar buildup and bad breath.", warning: "Monitor pet while chewing.", limit: "1 chew daily.", expiry: "Apr 2025", beforeUse: "Ensure fresh water is available.", imageUrl: "/images/medicines/dog_dental_chews.png" },
  { name: "Cat Anti-Hairball Paste", price: 290, category: "Pet Care", rating: 4.5, reviews: 85, uses: "Aids safe passage of swallowed hair.", warning: "Do not feed more than recommended.", limit: "2cm strip daily for 3 days.", expiry: "Jul 2026", beforeUse: "Can be placed on paw to lick.", imageUrl: "/images/medicines/cat_hairball_paste.png" },

  // Fitness & Wellness
  { name: "Resistance Bands Set", price: 600, category: "Fitness", rating: 4.8, reviews: 520, uses: "Strength training and physical therapy.", warning: "Inspect for tears before pulling.", limit: "Use per your workout routine.", expiry: "N/A", beforeUse: "Warm up before exercise.", imageUrl: "/images/medicines/resistance_bands.png" },
  { name: "Speed Jump Rope", price: 250, category: "Fitness", rating: 4.4, reviews: 150, uses: "Cardio workouts and warmups.", warning: "Use on flat surfaces to avoid tripping.", limit: "As tolerated.", expiry: "N/A", beforeUse: "Adjust length to height.", imageUrl: "/images/medicines/speed_jump_rope.png" },
  { name: "Massage Roller", price: 550, category: "Fitness", rating: 4.7, reviews: 290, uses: "Relieves muscle tension and knots.", warning: "Do not roll over joints or spine directly.", limit: "15 mins per muscle group.", expiry: "N/A", beforeUse: "Use on a yoga mat.", imageUrl: "https://placehold.co/400x400/8e44ad/ffffff?text=Deep+Tissue+Roller" },

  // General Medicine
  { name: "Men's Multivitamin", price: 650, category: "Medicine", rating: 4.6, reviews: 710, uses: "Daily vitamins targeting male health.", warning: "Do not exceed daily dosage.", limit: "1 tablet after breakfast.", expiry: "Nov 2026", beforeUse: "Swallow whole, do not chew.", imageUrl: "https://placehold.co/400x400/2980b9/ffffff?text=Mens+Multivitamins" },
  { name: "Women's Multivitamin", price: 650, category: "Medicine", rating: 4.7, reviews: 680, uses: "Daily vitamins including iron & calcium.", warning: "Store away from children to avoid iron overdose.", limit: "1 tablet after lunch.", expiry: "Nov 2026", beforeUse: "Take with food.", imageUrl: "https://placehold.co/400x400/e84393/ffffff?text=Womens+Multivitamins" },
  { name: "Electrolyte Powder", price: 120, category: "Medicine", rating: 4.9, reviews: 400, uses: "Restores hydration and essential salts.", warning: "Use cautiously if you have kidney disease.", limit: "Dissolve 1 sachet in 1 liter water.", expiry: "May 2027", beforeUse: "Stir until fully dissolved.", imageUrl: "https://placehold.co/400x400/f39c12/ffffff?text=Electrolytes" },
  { name: "Honey Cough Syrup", price: 110, category: "Medicine", rating: 4.5, reviews: 320, uses: "Soothes dry cough and throat irritation.", warning: "May cause slight drowsiness.", limit: "2 tsp every 6 hours.", expiry: "Oct 2025", beforeUse: "Shake well.", imageUrl: "https://placehold.co/400x400/d35400/ffffff?text=Honey+Cough+Syrup" },
  
  // Extension: 21 Newly Scaled Dynamic Catalog Items
  // Medicine
  { name: "Dolo 650mg", price: 30, category: "Medicine", rating: 4.6, reviews: 200, uses: "Relieves fever, headache, and body aches effectively.", warning: "Do not exceed 4000mg a day or mix with alcohol.", limit: "1 tablet every 6 hours.", expiry: "Dec 2026", beforeUse: "Store below 25°C.", imageUrl: "/images/medicines/dolo_650mg.png" },
  { name: "Azithromycin 500mg", price: 110, category: "Medicine", rating: 4.5, reviews: 85, uses: "Broad-spectrum antibiotic for bacterial infections.", warning: "Complete entire prescription course.", limit: "1 tablet per day for 3-5 days.", expiry: "Oct 2025", beforeUse: "Take 1 hour before or 2 hours after meals.", imageUrl: "/images/medicines/azithromycin_500mg.png" },
  { name: "Cough Syrup (Sugar-Free)", price: 95, category: "Medicine", rating: 4.7, reviews: 150, uses: "Relieves dry cough and throat irritation.", warning: "May cause slight drowsiness.", limit: "10ml thrice daily.", expiry: "Mar 2026", beforeUse: "Shake well before use.", imageUrl: "/images/medicines/cough_syrup.png" },
  { name: "Pantoprazole 40mg", price: 65, category: "Medicine", rating: 4.8, reviews: 140, uses: "Treats severe acidity and heartburn.", warning: "Take on an empty stomach.", limit: "1 tablet morning before breakfast.", expiry: "Jan 2027", beforeUse: "Do not chew or crush.", imageUrl: "/images/medicines/pantoprazole_40mg.png" },
  { name: "Diclofenac Gel", price: 85, category: "Medicine", rating: 4.4, reviews: 90, uses: "Topical relief for joint pain and sprains.", warning: "Do not apply on broken skin or wounds.", limit: "Apply 2-3 times daily gently.", expiry: "Aug 2025", beforeUse: "Wash hands after application.", imageUrl: "https://images.unsplash.com/photo-1629858639255-b46187514a60?q=80&w=400&fit=crop" },
  { name: "Vitamin D3 Capsules", price: 150, category: "Medicine", rating: 4.9, reviews: 210, uses: "Enhances calcium absorption for bone health.", warning: "Avoid overdose which may cause toxicity.", limit: "1 capsule per week as prescribed.", expiry: "Sep 2026", beforeUse: "Take after meals preferably with milk.", imageUrl: "/images/medicines/vitamin_d3_capsules.png" },

  // Device
  { name: "Weight Scale", price: 1299, category: "Device", rating: 4.6, reviews: 300, uses: "High-precision digital BMI and weight monitor.", warning: "Do not use with wet feet to prevent slipping.", limit: "Max carrying capacity 180kg.", expiry: "N/A (Warranty 1 yr)", beforeUse: "Place on a flat, hard surface.", imageUrl: "/images/medicines/weight_scale.png" },
  { name: "Heating Pad", price: 599, category: "Device", rating: 4.8, reviews: 450, uses: "Electric hot water bag for muscle cramps.", warning: "Do not puncture or plug while using on body.", limit: "Use for 15-20 min intervals.", expiry: "N/A", beforeUse: "Check for any wire damage.", imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=400&fit=crop" },
  { name: "Stethoscope", price: 850, category: "Device", rating: 4.7, reviews: 110, uses: "Classic dual-head acoustic heartbeat monitor.", warning: "Do not subject to extreme temperatures or solvents.", limit: "Unlimited usage.", expiry: "N/A", beforeUse: "Clean eartips regularly.", imageUrl: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?q=80&w=400&fit=crop" },

  // Personal Care
  { name: "Aloe Vera Gel", price: 199, category: "Personal Care", rating: 4.9, reviews: 520, uses: "Pure skin hydration and soothing for sunburns.", warning: "For external use only.", limit: "Apply generously as needed.", expiry: "Jul 2026", beforeUse: "Keep refrigerated for extra cooling.", imageUrl: "https://images.unsplash.com/photo-1611077544717-1996504a559e?q=80&w=400&fit=crop" },
  { name: "Anti-Dandruff Shampoo", price: 349, category: "Personal Care", rating: 4.5, reviews: 290, uses: "Clinically proven to reduce scalp flaking.", warning: "Avoid eye contact.", limit: "Use 2-3 times per week.", expiry: "Feb 2027", beforeUse: "Lather well and let sit for 2 mins.", imageUrl: "https://images.unsplash.com/photo-1629198725965-05e9d9976bb2?q=80&w=400&fit=crop" },

  // First Aid
  { name: "Antiseptic Liquid High Grade", price: 140, category: "First Aid", rating: 4.8, reviews: 330, uses: "Disinfects floors, surfaces, and minor wounds.", warning: "Corrosive if undiluted. Toxic if ingested.", limit: "Dilute 1 capful in 250ml water.", expiry: "Jun 2027", beforeUse: "Dilute before use.", imageUrl: "https://images.unsplash.com/photo-1584820927498-cafe0c1692ce?q=80&w=400&fit=crop" },
  { name: "Adhesive Plasters (100pcs)", price: 120, category: "First Aid", rating: 4.7, reviews: 600, uses: "Breathable bandages for minor cuts and scrapes.", warning: "Change daily or when wet.", limit: "Single use per plaster.", expiry: "Oct 2028", beforeUse: "Clean and dry wound first.", imageUrl: "https://images.unsplash.com/photo-1583947581924-860bda6a5a04?q=80&w=400&fit=crop" },
  { name: "Pain Relief Patch", price: 199, category: "First Aid", rating: 4.4, reviews: 150, uses: "Transdermal patch for fast sprain and back ache relief.", warning: "Do not apply over broken skin.", limit: "Keep on for up to 8 hours.", expiry: "Jan 2026", beforeUse: "Peel off securely.", imageUrl: "https://images.unsplash.com/photo-1610427958561-12c40cbf685a?q=80&w=400&fit=crop" },

  // Fitness
  { name: "Knee Cap Support", price: 350, category: "Fitness", rating: 4.6, reviews: 220, uses: "Provides orthopaedic joint compression during sports.", warning: "Do not wear while sleeping.", limit: "Wear during activity.", expiry: "N/A", beforeUse: "Check for proper sizing.", imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=400&fit=crop" },
  { name: "BCAA Amino Acids", price: 1599, category: "Fitness", rating: 4.8, reviews: 410, uses: "Prevents muscle breakdown and aids workout recovery.", warning: "Consult physician before use.", limit: "1 scoop during workout.", expiry: "Dec 2026", beforeUse: "Mix with 300ml cold water.", imageUrl: "https://images.unsplash.com/photo-1594882645126-14020914d58d?q=80&w=400&fit=crop" },

  // Pet Care
  { name: "Dog Deworming Tablets", price: 250, category: "Pet Care", rating: 4.9, reviews: 85, uses: "Effective broad-spectrum parasite control for dogs.", warning: "Not for pregnant dogs unless directed by vet.", limit: "1 tablet per 10kg body weight.", expiry: "Apr 2026", beforeUse: "Can be hidden in food.", imageUrl: "https://images.unsplash.com/photo-1606788075761-26dd66f7f0fa?q=80&w=400&fit=crop" },
  { name: "Liver Tonic for Pets", price: 320, category: "Pet Care", rating: 4.7, reviews: 110, uses: "Supports liver function and digestion in cats & dogs.", warning: "Only for animal use.", limit: "As directed by veterinarian.", expiry: "Nov 2025", beforeUse: "Shake well.", imageUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400&fit=crop" },

  // Ayush
  { name: "Brahmi Vati", price: 180, category: "Ayush", rating: 4.6, reviews: 175, uses: "Ayurvedic formulation to enhance memory and focus.", warning: "Avoid overdose.", limit: "1-2 tablets twice daily.", expiry: "May 2027", beforeUse: "Take with milk or warm water.", imageUrl: "https://images.unsplash.com/photo-1596541223130-5d56a73fb116?q=80&w=400&fit=crop" },
  { name: "Chyawanprash 500g", price: 310, category: "Ayush", rating: 4.9, reviews: 850, uses: "Traditional immunity builder rich in Vitamin C.", warning: "Diabetics must use sugar-free variant.", limit: "1-2 spoons daily.", expiry: "Jan 2026", beforeUse: "Best consumed with warm milk.", imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=400&fit=crop" },

  // Homeopathy
  { name: "Arnica Hair Oil", price: 210, category: "Homeopathy", rating: 4.5, reviews: 190, uses: "Controls hair fall and prevents premature graying.", warning: "For external scalp use only.", limit: "Massage deeply 2 times a week.", expiry: "Sep 2026", beforeUse: "Shake before application.", imageUrl: "https://images.unsplash.com/photo-1608248593842-8395f1712a32?q=80&w=400&fit=crop" },
  { name: "Nux Vomica 30CH", price: 110, category: "Homeopathy", rating: 4.4, reviews: 80, uses: "Fast acting homeopathic relief for digestion/acidity.", warning: "Avoid strong smells while taking medication.", limit: "4-5 globules 3 times a day.", expiry: "Dec 2028", beforeUse: "Do not touch globules with bare hands.", imageUrl: "https://images.unsplash.com/photo-1628771457497-7c050a41d73c?q=80&w=400&fit=crop" }
];
