const { sequelize, Medicine } = require('./models');

const products = [
  // First 17 use the AI images we successfully generated and saved locally
  { name: "Paracetamol 500mg", price: 30, category: "Medicine", rating: 4.5, reviews: 120, uses: "Relieves mild to moderate pain and reduces fever.", warning: "Do not exceed 4000mg per day. Avoid alcohol.", limit: "1-2 tablets every 4-6 hours max.", expiry: "Dec 2026", beforeUse: "Store below 25°C in a dry place.", imageUrl: "/images/medicines/paracetamol_500mg_1774028012018.png" },
  { name: "Vitamin C Tablets", price: 50, category: "Medicine", rating: 4.8, reviews: 85, uses: "Boosts immune system and treats vitamin C deficiency.", warning: "High doses may cause stomach cramps or diarrhea.", limit: "1 tablet daily after meal.", expiry: "Mar 2026", beforeUse: "Keep bottle tightly closed.", imageUrl: "/images/medicines/vitamin_c_tablets_1774028034331.png" },
  { name: "Amoxicillin", price: 80, category: "Medicine", rating: 4.2, reviews: 45, uses: "Antibiotic used to treat bacterial infections.", warning: "Requires prescription. Complete full course. May cause allergic reactions in some.", limit: "Usually 500mg every 8-12 hours.", expiry: "Oct 2025", beforeUse: "Consume full course once started.", imageUrl: "/images/medicines/amoxicillin_1774028052407.png" },
  { name: "Cetirizine", price: 40, category: "Medicine", rating: 4.6, reviews: 60, uses: "Treats allergic symptoms like sneezing, runny nose.", warning: "May cause drowsiness. Do not drive if affected.", limit: "1 tablet per day.", expiry: "Jan 2027", beforeUse: "Protect from direct sunlight.", imageUrl: "/images/medicines/cetirizine_1774028069738.png" },
  { name: "Aspirin 100mg", price: 25, category: "Medicine", rating: 4.3, reviews: 30, uses: "Pain relief and blood thinner to prevent heart attacks.", warning: "Do not give to children. May cause stomach bleeding.", limit: "As directed by a doctor.", expiry: "Nov 2025", beforeUse: "Do not use if seal is broken.", imageUrl: "/images/medicines/aspirin_100mg_1774028090847.png" },
  { name: "Metformin 500mg", price: 65, category: "Medicine", rating: 4.7, reviews: 110, uses: "Controls high blood sugar in type 2 diabetes.", warning: "May cause lactic acidosis. Take with meals.", limit: "Max 2000mg/day depending on doctor prescription.", expiry: "Aug 2026", beforeUse: "Store below 30°C.", imageUrl: "/images/medicines/metformin_500mg_1774028108849.png" },
  { name: "Atorvastatin 10mg", price: 120, category: "Medicine", rating: 4.4, reviews: 95, uses: "Lowers 'bad' cholesterol and fats in blood.", warning: "May cause muscle pain. Avoid grapefruit juice.", limit: "1 tablet daily.", expiry: "Sep 2026", beforeUse: "Keep out of reach of children.", imageUrl: "/images/medicines/atorvastatin_10mg_1774028129882.png" },
  { name: "Digital Thermometer", price: 150, category: "Device", rating: 4.5, reviews: 200, uses: "Measures body temperature accurately.", warning: "Keep out of reach of infants. Do not immerse in boiling water.", limit: "No usage limit, change battery periodically.", expiry: "N/A (Battery ~2 yrs)", beforeUse: "Calibrate before first use.", imageUrl: "/images/medicines/digital_thermometer_1774028145612.png" },
  { name: "BP Monitor", price: 1200, category: "Device", rating: 4.9, reviews: 150, uses: "Monitors blood pressure levels at home.", warning: "Not a substitute for doctor consultation. Calibrate yearly.", limit: "Use as needed.", expiry: "N/A (Warranty 3 yrs)", beforeUse: "Read manual thoroughly.", imageUrl: "/images/medicines/bp_monitor_1774028164696.png" },
  { name: "Pulse Oximeter", price: 899, category: "Device", rating: 4.6, reviews: 80, uses: "Measures blood oxygen levels (SpO2) and pulse.", warning: "Nail polish may affect reading accuracy.", limit: "Use as needed.", expiry: "N/A (Warranty 1 yr)", beforeUse: "Clean sensor before use.", imageUrl: "/images/medicines/pulse_oximeter_1774028180159.png" },
  { name: "Glucometer Kit", price: 1450, category: "Device", rating: 4.8, reviews: 65, uses: "Monitors blood glucose levels for diabetics.", warning: "Use fresh test strips. Do not share lancets.", limit: "Depends on monitoring frequency prescribed.", expiry: "Strips exp: Aug 2025", beforeUse: "Check strip codes match meter.", imageUrl: "/images/medicines/glucometer_kit_1774028208155.png" },
  { name: "Nebulizer Machine", price: 2100, category: "Device", rating: 4.3, reviews: 40, uses: "Delivers medication directly to the lungs.", warning: "Clean parts after every use to prevent infection.", limit: "Use as prescribed for respiratory conditions.", expiry: "N/A (Warranty 2 yrs)", beforeUse: "Sterilize attachments.", imageUrl: "/images/medicines/nebulizer_machine_1774028228172.png" },
  { name: "Face Wash", price: 199, category: "Personal Care", rating: 4.2, reviews: 300, uses: "Cleanses skin and removes impurities.", warning: "Avoid contact with eyes. For external use only.", limit: "Use twice daily.", expiry: "May 2026", beforeUse: "Use within 6 months of opening.", imageUrl: "/images/medicines/face_wash_1774028241826.png" },
  { name: "Hand Sanitizer", price: 99, category: "Personal Care", rating: 4.5, reviews: 500, uses: "Kills 99.9% germs on hands instantly.", warning: "Flammable. Keep away from fire. Do not swallow.", limit: "Use as needed.", expiry: "Jul 2025", beforeUse: "Keep away from heat.", imageUrl: "/images/medicines/hand_sanitizer_1774028262239.png" },
  { name: "Sunscreen SPF 50", price: 450, category: "Personal Care", rating: 4.7, reviews: 180, uses: "Protects skin from harmful UV sun rays.", warning: "Reapply every 2-3 hours if swimming or sweating.", limit: "Apply generously 15 mins before sun exposure.", expiry: "Apr 2026", beforeUse: "Shake well before use.", imageUrl: "/images/medicines/sunscreen_spf_50_1774028279799.png" },
  { name: "Moisturizing Lotion", price: 320, category: "Personal Care", rating: 4.6, reviews: 220, uses: "Hydrates and softens dry skin.", warning: "If irritation occurs, discontinue use.", limit: "Apply daily as required.", expiry: "Jan 2027", beforeUse: "Use within 12 months of opening.", imageUrl: "/images/medicines/moisturizing_lotion_1774028295234.png" },
  { name: "Surgical Mask (50pcs)", price: 250, category: "Surgicals", rating: 4.8, reviews: 1000, uses: "Provides protection against airborne particles.", warning: "Single use only. Do not wash and reuse.", limit: "Change every 4-6 hours or if soiled.", expiry: "Feb 2028", beforeUse: "Store in dry place.", imageUrl: "/images/medicines/surgical_mask_1774028314475.png" },
  
  // The remaining 15 items use ultra high quality distinct Unsplash photography because the external AI generative API was totally blocked.
  { name: "Crepe Bandage", price: 110, category: "Surgicals", rating: 4.1, reviews: 50, uses: "Provides support for sprains and strains.", warning: "Do not wrap too tightly; may restrict blood flow.", limit: "Use as needed until healed.", expiry: "N/A (Replace when stretched)", beforeUse: "Wash gently if reused.", imageUrl: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=400&fit=crop" },
  { name: "Sterile Gauze", price: 45, category: "Surgicals", rating: 4.4, reviews: 75, uses: "For cleaning and covering wounds.", warning: "Do not use if package is opened or damaged.", limit: "Change daily or as instructed by doctor.", expiry: "Sep 2027", beforeUse: "Use immediately upon opening.", imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=400&fit=crop" },
  { name: "Fitness Band", price: 2499, category: "Fitness", rating: 4.5, reviews: 400, uses: "Tracks steps, heart rate, and workouts.", warning: "Not a medical device. Measurements are estimates.", limit: "Wear continuously if desired.", expiry: "N/A", beforeUse: "Charge fully before first use.", imageUrl: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b2?q=80&w=400&fit=crop" },
  { name: "Whey Protein 1kg", price: 1899, category: "Fitness", rating: 4.9, reviews: 600, uses: "Helps in muscle building and recovery.", warning: "Consult doctor if you have kidney issues. Contains dairy.", limit: "Usually 1-2 scoops per day based on workout.", expiry: "Mar 2025", beforeUse: "Consume within 3 months of opening.", imageUrl: "https://images.unsplash.com/photo-1574015974293-817f0ebebb74?q=80&w=400&fit=crop" },
  { name: "Yoga Mat", price: 799, category: "Fitness", rating: 4.7, reviews: 350, uses: "Provides cushioning and non-slip surface for exercise.", warning: "Keep away from direct sharp objects or prolonged sun.", limit: "Use as needed.", expiry: "N/A", beforeUse: "Wipe with damp cloth.", imageUrl: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=400&fit=crop" },
  { name: "Pet Shampoo", price: 299, category: "Pet Care", rating: 4.6, reviews: 120, uses: "Cleanses and deodorizes pet's coat.", warning: "Avoid contact with pets' eyes and ears.", limit: "Use once every 1-2 weeks.", expiry: "Oct 2026", beforeUse: "Dilute with water before use.", imageUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400&fit=crop" },
  { name: "Tick & Flea Spray", price: 450, category: "Pet Care", rating: 4.3, reviews: 90, uses: "Kills and repels ticks, fleas, and lice on pets.", warning: "Do not spray on eyes or mouth. Wash hands after use.", limit: "Apply based on product instructions.", expiry: "Nov 2025", beforeUse: "Shake vigorously.", imageUrl: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=400&fit=crop" },
  { name: "Pet Multivitamins", price: 350, category: "Pet Care", rating: 4.8, reviews: 55, uses: "Supports overall pet health and immunity.", warning: "For animal use only. Keep out of reach of children.", limit: "Usually 1 tablet/syrup dose daily.", expiry: "Jul 2025", beforeUse: "Store tightly sealed.", imageUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?q=80&w=400&fit=crop" },
  { name: "Ayush Kadha", price: 180, category: "Ayush", rating: 4.7, reviews: 250, uses: "Ayurvedic immunity booster to fight cold/cough.", warning: "May cause mild heat in body, avoid overconsumption.", limit: "1 cup daily.", expiry: "Dec 2026", beforeUse: "Mix well in boiling water.", imageUrl: "https://images.unsplash.com/photo-1564858025217-48f07fb0b9fe?q=80&w=400&fit=crop" },
  { name: "Ashwagandha Powder", price: 240, category: "Ayush", rating: 4.6, reviews: 140, uses: "Reduces stress and boosts energy optionally.", warning: "Pregnant women should consult a doctor before use.", limit: "1/2 to 1 tsp daily with milk or water.", expiry: "Aug 2025", beforeUse: "Keep away from moisture.", imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=400&fit=crop" },
  { name: "Triphala Churna", price: 150, category: "Ayush", rating: 4.5, reviews: 110, uses: "Relieves constipation and improves digestion.", warning: "Overuse may cause loose stools. Consult physician.", limit: "1 tsp before sleep.", expiry: "Feb 2026", beforeUse: "Consume with lukewarm water.", imageUrl: "https://images.unsplash.com/photo-1596541223130-5d56a73fb116?q=80&w=400&fit=crop" },
  { name: "Homeo Cold Drops", price: 95, category: "Homeopathy", rating: 4.2, reviews: 85, uses: "Homeopathic remedy for runny nose and cold.", warning: "Keep 30 mins gap between meals and medicine.", limit: "10-15 drops in water, 3 times a day.", expiry: "Jan 2027", beforeUse: "Store away from strong odors.", imageUrl: "https://images.unsplash.com/photo-1628771457497-7c050a41d73c?q=80&w=400&fit=crop" },
  { name: "Homeo Digest Syrup", price: 130, category: "Homeopathy", rating: 4.4, reviews: 60, uses: "Alleviates indigestion, gas, and acidity naturally.", warning: "Keep away from strong-smelling substances like camphor.", limit: "1-2 teaspoons thrice daily.", expiry: "Jun 2026", beforeUse: "Shake well before use.", imageUrl: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?q=80&w=400&fit=crop" },
  { name: "Ibuprofen 400mg", price: 45, category: "Medicine", rating: 4.6, reviews: 310, uses: "Relieves pain from various conditions such as headache, dental pain, menstrual cramps.", warning: "Take with food to prevent stomach upset.", limit: "Every 6-8 hours as needed. Max 3200mg/day.", expiry: "Oct 2027", beforeUse: "Store at room temperature.", imageUrl: "https://images.unsplash.com/photo-1550572017-edb79a0cfb2e?q=80&w=400&fit=crop" },
  { name: "Omeprazole 20mg", price: 55, category: "Medicine", rating: 4.8, reviews: 154, uses: "Treats certain stomach and esophagus problems (such as acid reflux, ulcers).", warning: "May take 1 to 4 days for full effect.", limit: "1 capsule daily before a meal.", expiry: "Sep 2026", beforeUse: "Do not chew or crush.", imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=400&fit=crop" }
];

sequelize.sync({ force: true }).then(async () => {
  console.log("Database synced. Seeding data...");
  await Medicine.bulkCreate(products);
  console.log("Data Seeded Successfully.");
  process.exit();
}).catch(err => {
  console.error("Error seeding:", err);
  process.exit(1);
});
